single role execution

diff --git a/bin/run b/bin/run
--- a/bin/run
+++ b/bin/run
@@ -6,21 +6,38 @@
 
 BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
 MASTER_PLAYBOOK="osx"
+MASTER_ROLE="all"
 
 if ! which ansible-playbook &>/dev/null; then
   echo "Failed to locate 'ansible-playbook' utility." && exit 1
 fi
 
-if [ ! -z $1 ]; then
+if [[ ! -z $1 && ! -z $2 ]]; then
+  MASTER_PLAYBOOK="${BASE_DIR}/run_role.yml"
+elif [ ! -z $1 ]; then
   MASTER_PLAYBOOK="${BASE_DIR}/${1}.yml"
-  if [ ! -f $MASTER_PLAYBOOK ]; then
-    echo "Failed to locate '$(basename $MASTER_PLAYBOOK)' playbook." && exit 1
-  fi
 else
   MASTER_PLAYBOOK="${BASE_DIR}/${MASTER_PLAYBOOK}.yml"
 fi
 
-ansible-playbook $MASTER_PLAYBOOK
+if [ ! -f $MASTER_PLAYBOOK ]; then
+  echo "Failed to locate '$(basename $MASTER_PLAYBOOK)' playbook." && exit 1
+fi
+
+if [ ! -z $2 ]; then
+  MASTER_ROLE="${BASE_DIR}/roles/${2}"
+fi
+
+if [[ $MASTER_ROLE != "all" && ! -d $MASTER_ROLE ]]; then
+  echo "Failed to locate '$(basename ${MASTER_PLAYBOOK%.*})/$(basename $MASTER_ROLE)' role." && exit 1
+fi
+
+ANSIBLE_ARGS=""
+if [[ $MASTER_ROLE != "all" && ! -z $MASTER_ROLE ]]; then
+  ANSIBLE_ARGS="--extra-vars role=$(basename ${MASTER_ROLE})"
+fi
+
+ansible-playbook $MASTER_PLAYBOOK $ANSIBLE_ARGS
 
 echo "Done."
 exit 0
